{{- if has "transaction-approval" .Values.global.modules }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: transaction-approval-deny-rules
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
      exceptions:
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            jsonPath: "$.username"
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^filter$"
                ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ .Values.global.path.transactionApproval }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false

{{- end }}